---

- name: Change passwords in specific Linux user accounts
  hosts: all
  
  vars:
    # Define the list of users and their new passwords
    username: prueba
    password: 'asdf1234' 

  tasks:
    - name: Verify the user exist before changing password
      ansible.builtin.getent:
        database: passwd
        key: "{{ username }}"
      register: user_check
      failed_when: false

    - name: Display warning for non-existent user
      ansible.builtin.fail:
        msg: "WARNING: User {{ username }} does not exist on this system"
      when: user_check is not defined or username not in user_check.ansible_facts.getent_passwd

    - name: Change user passwords
      ansible.builtin.user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        update_password: always
      when:
        - user_check.ansible_facts is defined
        - user_check.ansible_facts.getent_passwd is defined
        - username in user_check.ansible_facts.getent_passwd
      no_log: false

    # - name: Force password expiry (optional - uncomment if needed)
    #   ansible.builtin.command:
    #     cmd: "chage -d 0 {{ item.username }}"
    #   loop: "{{ users_passwords }}"
    #   when: force_password_change_on_login | default(false)
    #   changed_when: true

    - name: Display completion message
      ansible.builtin.debug:
        msg: "Password change process completed for user: '{{ username }}'. Please ensure to test the new password."
...
