---
- name: Change Linux user passwords
  hosts: all
  vars:
    # Define the list of users and their new passwords
    users_passwords:
      - username: user1
        password: 'passwd1'

  tasks:
    - name: Verify users exist before changing passwords
      ansible.builtin.getent:
        database: passwd
        key: "{{ item.username }}"
      loop: "{{ users_passwords }}"
      register: user_check
      failed_when: false

    - name: Display warning for non-existent users
      ansible.builtin.debug:
        msg: "WARNING: User {{ item.item.username }} does not exist on this system"
      loop: "{{ user_check.results }}"
      when: item.ansible_facts is not defined or item.ansible_facts.getent_passwd is not defined

    - name: Change user passwords
      ansible.builtin.user:
        name: "{{ item.item.username }}"
        password: "{{ item.item.password | password_hash('sha512') }}"
        update_password: always
      loop: "{{ user_check.results }}"
      when:
        - item.ansible_facts is defined
        - item.ansible_facts.getent_passwd is defined
        - item.item.username in item.ansible_facts.getent_passwd
      no_log: false

    # - name: Force password expiry (optional - uncomment if needed)
    #   ansible.builtin.command:
    #     cmd: "chage -d 0 {{ item.username }}"
    #   loop: "{{ users_passwords }}"
    #   when: force_password_change_on_login | default(false)
    #   changed_when: true

    - name: Display completion message
      ansible.builtin.debug:
        msg: "Password change process completed for all specified users"
...
